//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("VRCGalleryManager")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("TheIceDragonz")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Simple Tool for your VRChat gallery")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.1")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+e31745feacfed3bc7eb755c4028a88ac4c466814")]
[assembly: System.Reflection.AssemblyProductAttribute("VRCGalleryManager")]
[assembly: System.Reflection.AssemblyTitleAttribute("VRCGalleryManager")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.1")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/TheIceDragonz/VRCGalleryManager")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")]

// Generato dalla classe WriteCodeFragment di MSBuild.

